---
title: "PeHa data check"
author: "Michelle DePrenger-Levin"
date: "Thursday, September 10, 2015"
output: html_document
---
```{r}
library(ggplot2)
library(reshape2)
library(reshape)
```

ctrl+Alt+c will run a chunck of code

gather climate data from WWDT and/or <http://www.prism.oregonstate.edu/explorer/>
First 6 lines of code are metadata
first column is YYYY-MM and then data in metric

```{r}
ae_p <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/AE_precip_2015.csv"), skip=6)
head(ae_p)
dl_p <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/DL_precip_2015.csv"), skip=6)
ae_tmax <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/AE_tmax_2015.csv"), skip=6)
dl_tmax <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/DL_maxtemp_2015.csv"), skip=6)
ae_tmin <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/AE_tmin_2015.csv"), skip=6)
dl_tmin <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/DL_tmin_2015.csv"), skip=6)

ae.climate <- data.frame(ae_p,ae_tmax,ae_tmin)
head(ae.climate)
ae.climate$Site <- "Above Eagle"

dl.climate <- data.frame(dl_p,dl_tmax,dl_tmin)
head(dl.climate)
dl.climate$Site <- "Dry Lake"

peha.climate <- rbind(ae.climate,dl.climate)
peha.climate$Year <- substr(ae.climate$Date,1,4)
peha.climate$Month <- substr(ae.climate$Date,6,7)

head(peha.climate)
peha.c <- peha.climate[,c(1,2,4,6:9)]
names(peha.c) <- c("Date","Precip","Tmax","Tmin","Site","Year","Month")
peha.c$Date <- as.Date(paste(peha.climate$Date,"01", sep="-")) # needs the day

table(peha.c$Site, peha.c$Precip)

ggplot(peha.c, aes(Date, Tmin, colour = Site)) +
  geom_point()

lapply(peha.c[,2:4], function(x) mean(x, na.rm = TRUE))
avg_peha <- by(peha.c[,5:6], peha.c[,2:4], function(x) mean(x, na.rm = TRUE))

tapply(peha.c[,5:6], peha.c[,2:4], mean)
peha.precip <- tapply(peha.c[,2], peha.c[,6], function(x) mean(x, na.rm = TRUE))
peha.tmax <- tapply(peha.c[,3], peha.c[,6], function(x) mean(x, na.rm = TRUE))
peha.tmin <- tapply(peha.c[,4], peha.c[,6], function(x) mean(x, na.rm = TRUE))
climate <- data.frame(peha.precip,peha.tmax,peha.tmin, Year = row.names(peha.precip))

#expand.grid(unique(peha.c$Site),unique(peha.c$Year))



```

The old data gave me different values by site for precipitation 

```{r}
peha_sum <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/peha_2015_summary.csv"))

head(peha_sum)
tail(peha_sum)
ggplot(peha_sum, aes(Year,Jan)) +
  geom_line() +
  facet_wrap(~Site)
```



```{r}
peha <- read.csv(path.expand("Q:/Research/All_Projects_by_Species/Penstemon SPECIES/Penstemon_harringtonii/R_code_PeHa/R_tables/peha2015.csv"))

head(peha)
table(peha$Site, peha$Year)
```



```{r, echo=FALSE}
ggplot(peha, aes(Year, X.ofRosettes)) +
  geom_bar(stat='identity') +
  facet_grid(~Site)
```



```{r, echo=FALSE}
ggplot(peha, aes(Year, X.ofRosettes)) +
  stat_summary(fun.y = sum, geom="line") +
  facet_wrap(~Site)
```



```{r, echo=FALSE}
ggplot(peha, aes(Year, X.ofRosettes, colour = Site)) +
  stat_summary(fun.y = sum, geom="line") +
  ylab("Total Rosettes")
```


